server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  auth_basic "Weight Stats";
  auth_basic_user_file /etc/nginx/.htpasswd;

  location /api/ {
    proxy_pass http://weight-stats-be:8083;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
